#cloud-config
users:
  - name: sacloud-user
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: wheel,adm,systemd-journal
    ssh_authorized_keys: ${ssh_pubkey}
chpasswd:
  expire: false
  users:
    - {name: root, password: ${password} , type: text}
    - {name: sacloud-user, password: ${password} , type: text}
ssh_pwauth: false
bootcmd:
  - sed -i -e 's/^\SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config
  - setenforce 0
  - sysctl -p
  - grubby --update-kernel ALL --args selinux=0
  - [localectl, set-keymap, jp]
  - [localectl, set-x11-keymap, jp]
  - hostnamectl hostname ${hostname}
runcmd:
  - nmcli c m "System eth0" connection.autoconnect yes
  - nmcli c m "System eth0" ipv4.address "${ip_address}/${netmask}" ipv4.gateway "${gateway}"
  - nmcli c m "System eth0" ipv4.dns "8.8.8.8"
  - nmcli c m "System eth0" ipv4.method manual
  - nmcli c up "System eth0"
  - rpm -Uvh https://repo.zabbix.com/zabbix/7.0/alma/9/x86_64/zabbix-release-7.0-2.el9.noarch.rpm
  - dnf clean all
  - dnf install -y glibc-langpack-ja
  - localectl set-locale LANG=ja_JP.utf8
  - dnf install -y zabbix-server-pgsql zabbix-web-pgsql zabbix-nginx-conf zabbix-sql-scripts zabbix-selinux-policy zabbix-agent
  - dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
  - dnf install -y postgresql15-server
  - postgresql-setup --initdb
  - PGSETUP_INITDB_OPTIONS='--encoding=UTF-8 --no-locale' postgresql-15-setup initdb
  - systemctl enable postgresql-15
  - systemctl start postgresql-15
  - sudo -u postgres psql -c "create user zabbix password 'zabbix';"
  - sudo -u postgres createdb -O zabbix zabbix
  - zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix
  - sed -i "s/# DBPassword=/DBPassword=zabbix/g" /etc/zabbix/zabbix_server.conf 
  - sed -i "s/#        listen          8080;/        listen          8080;/g" /etc/nginx/conf.d/zabbix.conf
  - systemctl restart zabbix-server zabbix-agent nginx php-fpm
  - systemctl enable zabbix-server zabbix-agent nginx php-fpm
  - grubby --update-kernel ALL --args selinux=0
  - reboot
